name: multitasking
version: 3.8.0
description: Cooperative multitasking using asynchronous tasks and synchronization primitives, with the ability to safely cancel groups of nested tasks performing I/O wait or listen operations.
homepage: https://github.com/mezoni/multitasking
topics:
 - parallelism
 - concurrency
 - cancellation
 - synchronization
 - mutex
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async: ^2.13.0
  meta:
  stack_trace:
dev_dependencies:
  defer:
  http:
  lints:
  test:
