name: multitasking
version: 5.3.0
description: Cooperative multitasking using asynchronous tasks and synchronization primitives, with the ability to safely cancel groups of nested tasks performing I/O wait or listen operations.
homepage: https://github.com/mezoni/multitasking
topics:
 - concurrency
 - cancellation
 - synchronization
 - mutex
 - streams
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async: ^2.13.0
  meta: ^1.18.2
  stack_trace: ^1.12.1
dev_dependencies:
  defer: ^1.0.0
  http: ^1.6.0
  lints: ^6.1.0
  test: ^1.31.0
  typed_data: ^1.4.0
